name: Playwright Test

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Playwright and Dependencies
        run: npx playwright install --with-deps chromium firefox

      - name: Install Allure Command Line and Allure-Playwright adapter
        run: npm install allure-commandline allure-playwright --save-dev

      - name: Install Faker
        run: npm install @faker-js/faker --save-dev

      - name: Generate Timestamp for Unique Folder Name
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%d%H%M%S")"

      - name: Run Tests
        run: npx playwright test
        continue-on-error: true

      - name: Set Git User
        run: |
          git config --global user.email "serge.karpov@gmail.com"
          git config --global user.name "SHIRO SAN"
