name: Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright and Dependencies
        run: npx playwright install --with-deps chromium firefox

      - name: Install Allure Command Line and Allure-Playwright adapter
        run: npm install --save-dev allure-commandline allure-playwright

      - name: Generate Timestamp for Unique Folder Name
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%d%H%M%S")"

      - name: Set Git User
        run: |
          git config --global user.email "serge.karpov@gmail.com"
          git config --global user.name "SHIRO SAN"

      - name: Create and Switch to allure-report Branch
        run: |
          git checkout -b allure-report
          git push --set-upstream origin allure-report

      - name: Run Tests
        run: npx playwright test
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          # Move the allure-results directory to a unique timestamped folder for historical data
          mv allure-results $GITHUB_WORKSPACE/allure-reports/$timestamp

          # Generate the Allure report
          npx allure generate --clean -o allure-reports/$timestamp

          # Move the updated allure-report directory back to the workspace
          mv allure-reports/$timestamp $GITHUB_WORKSPACE/allure-reports/$timestamp

      - name: Commit and Push Allure Report
        run: |
          git add -A
          git commit -m "Add Allure report"
          git push --force origin allure-report