name: Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright and Dependencies
        run: npx playwright install --with-deps chromium firefox

      - name: Install Allure Command Line and Allure-Playwright adapter
        run: npm install allure-commandline allure-playwright --save-dev

      - name: Install Faker
        run: npm install @faker-js/faker --save-dev

      - name: Run Tests
        run: npx playwright test
        continue-on-error: true

      - name: Set Git User
        run: |
          git config --global user.email "serge.karpov@gmail.com"
          git config --global user.name "SHIRO SAN"

      - name: Configure GitHub Pages
        run: |
          # Create or switch to the gh-pages branch
          git checkout -B gh-pages

          # Remove existing content (if any)
          git rm -r .

          # Commit the changes
          git commit -m "Initial commit for GitHub Pages"
          
          # Push the changes to the gh-pages branch
          git push --force origin gh-pages

      - name: Copy Allure Report Data
        run: |
          mkdir -p $GITHUB_WORKSPACE/allure-report
          cp -r allure-results/* $GITHUB_WORKSPACE/allure-report

      - name: Push Report to Another Branch
        run: |
          git checkout -b allure-report
          git add -A
          git commit -m "Add Allure report"
          git push --force origin allure-report
        env:
          PAT: ${{ secrets.MY_SECRET_CAT }}

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Configure GitHub Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
