name: Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright and Dependencies
        run: npx playwright install --with-deps chromium firefox

      - name: Install Allure Command Line and Allure-Playwright adapter
        run: npm install allure-commandline allure-playwright --save-dev

      - name: Install Faker
        run: npm install @faker-js/faker --save-dev

      - name: Generate Timestamp for Unique Folder Name
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%d%H%M%S")"

      - name: Set Git User
        run: |
          git config --global user.email "serge.karpov@gmail.com"
          git config --global user.name "SHIRO SAN"

      - name: Create and Switch to allure-report Branch
        run: |
          git checkout -b allure-report
          git push --set-upstream origin allure-report
          
      - name: Copy Allure Report Data
        run: |
          mkdir -p $GITHUB_WORKSPACE/allure-report
          # Loop through the files in the source directory
          for file in ./allure-results/*; do
            # Get the file name without the path
            filename=$(basename "$file")
            # Check if the file already exists in the destination directory
            if [ ! -e "$GITHUB_WORKSPACE/allure-report/$filename" ]; then
              # If the file doesn't exist in the destination, copy it
              cp "$file" "$GITHUB_WORKSPACE/allure-report/$filename"
            fi
          done

      - name: Run Tests
        run: npx playwright test
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate --clean
          mv allure-report $GITHUB_WORKSPACE/allure-report

      - name: Commit and Push Allure Report
        run: |
          git add -A
          git commit -m "Add Allure report"
          git push --force origin allure-report
